version: '3'
services:
  visualizador:
    image: dockersamples/visualizer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager


  api:
    image: vdiniz001/fiap_api01 
    deploy:
      replicas: 1
    ports:
      - 8001:8080
