kind: Service
apiVersion: v1
metadata:
  name: model-api01-service
spec:
  selector:
    app: api01
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort