kind: Service
apiVersion: v1
metadata:
  name: model-fiap-service-lb
spec:
  selector:
    app: api01
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      #nodePort: 31000
  type: LoadBalancer

kind: Service
apiVersion: v1
metadata:
  name: model-fiap-service-np
spec:
  selector:
    app: api01
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort